// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.anime.protoc.items

@SerialVersionUID(0L)
final case class Items(
    sums: _root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.AnimeSummary] = _root_.scala.collection.Seq.empty,
    cache: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime] = scala.collection.immutable.Map.empty,
    anime: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser] = scala.collection.immutable.Map.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Items] with scalapb.lenses.Updatable[Items] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      sums.foreach(sums => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(sums.serializedSize) + sums.serializedSize)
      cache.foreach(cache => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase(cache).serializedSize) + com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase(cache).serializedSize)
      anime.foreach(anime => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase(anime).serializedSize) + com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase(anime).serializedSize)
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      sums.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
      cache.foreach { __v =>
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase(__v).serializedSize)
        com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase(__v).writeTo(_output__)
      };
      anime.foreach { __v =>
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase(__v).serializedSize)
        com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase(__v).writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.github.sguzman.anime.protoc.items.Items = {
      val __sums = (_root_.scala.collection.immutable.Vector.newBuilder[com.github.sguzman.anime.protoc.items.AnimeSummary] ++= this.sums)
      val __cache = (scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime] ++= this.cache)
      val __anime = (scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser] ++= this.anime)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __sums += _root_.scalapb.LiteParser.readMessage(_input__, com.github.sguzman.anime.protoc.items.AnimeSummary.defaultInstance)
          case 18 =>
            __cache += com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, com.github.sguzman.anime.protoc.items.Items.CacheEntry.defaultInstance))
          case 26 =>
            __anime += com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, com.github.sguzman.anime.protoc.items.Items.AnimeEntry.defaultInstance))
          case tag => _input__.skipField(tag)
        }
      }
      com.github.sguzman.anime.protoc.items.Items(
          sums = __sums.result(),
          cache = __cache.result(),
          anime = __anime.result()
      )
    }
    def clearSums = copy(sums = _root_.scala.collection.Seq.empty)
    def addSums(__vs: com.github.sguzman.anime.protoc.items.AnimeSummary*): Items = addAllSums(__vs)
    def addAllSums(__vs: TraversableOnce[com.github.sguzman.anime.protoc.items.AnimeSummary]): Items = copy(sums = sums ++ __vs)
    def withSums(__v: _root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.AnimeSummary]): Items = copy(sums = __v)
    def clearCache = copy(cache = scala.collection.immutable.Map.empty)
    def addCache(__vs: (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)*): Items = addAllCache(__vs)
    def addAllCache(__vs: TraversableOnce[(_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)]): Items = copy(cache = cache ++ __vs)
    def withCache(__v: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime]): Items = copy(cache = __v)
    def clearAnime = copy(anime = scala.collection.immutable.Map.empty)
    def addAnime(__vs: (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)*): Items = addAllAnime(__vs)
    def addAllAnime(__vs: TraversableOnce[(_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)]): Items = copy(anime = anime ++ __vs)
    def withAnime(__v: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser]): Items = copy(anime = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => sums
        case 2 => cache.map(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase)(_root_.scala.collection.breakOut)
        case 3 => anime.map(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase)(_root_.scala.collection.breakOut)
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(sums.map(_.toPMessage)(_root_.scala.collection.breakOut))
        case 2 => _root_.scalapb.descriptors.PRepeated(cache.map(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toBase(_).toPMessage)(_root_.scala.collection.breakOut))
        case 3 => _root_.scalapb.descriptors.PRepeated(anime.map(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toBase(_).toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.github.sguzman.anime.protoc.items.Items
}

object Items extends scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.sguzman.anime.protoc.items.Items = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.github.sguzman.anime.protoc.items.Items(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.AnimeSummary]],
      __fieldsMap.getOrElse(__fields.get(1), Nil).asInstanceOf[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.Items.CacheEntry]].map(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toCustom)(_root_.scala.collection.breakOut),
      __fieldsMap.getOrElse(__fields.get(2), Nil).asInstanceOf[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.Items.AnimeEntry]].map(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toCustom)(_root_.scala.collection.breakOut)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.github.sguzman.anime.protoc.items.Items] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.github.sguzman.anime.protoc.items.Items(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.AnimeSummary]]).getOrElse(_root_.scala.collection.Seq.empty),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.Items.CacheEntry]]).getOrElse(_root_.scala.collection.Seq.empty).map(com.github.sguzman.anime.protoc.items.Items._typemapper_cache.toCustom)(_root_.scala.collection.breakOut),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.Items.AnimeEntry]]).getOrElse(_root_.scala.collection.Seq.empty).map(com.github.sguzman.anime.protoc.items.Items._typemapper_anime.toCustom)(_root_.scala.collection.breakOut)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ItemsProto.javaDescriptor.getMessageTypes.get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ItemsProto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.github.sguzman.anime.protoc.items.AnimeSummary
      case 2 => __out = com.github.sguzman.anime.protoc.items.Items.CacheEntry
      case 3 => __out = com.github.sguzman.anime.protoc.items.Items.AnimeEntry
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq[_root_.scalapb.GeneratedMessageCompanion[_]](
    _root_.com.github.sguzman.anime.protoc.items.Items.CacheEntry,
    _root_.com.github.sguzman.anime.protoc.items.Items.AnimeEntry
  )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.github.sguzman.anime.protoc.items.Items(
  )
  @SerialVersionUID(0L)
  final case class CacheEntry(
      key: _root_.scala.Predef.String = "",
      value: scala.Option[com.github.sguzman.anime.protoc.items.Anime] = None
      ) extends scalapb.GeneratedMessage with scalapb.Message[CacheEntry] with scalapb.lenses.Updatable[CacheEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        if (key != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, key) }
        if (value.isDefined) { __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(value.get.serializedSize) + value.get.serializedSize }
        __size
      }
      final override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        };
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.github.sguzman.anime.protoc.items.Items.CacheEntry = {
        var __key = this.key
        var __value = this.value
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = Option(_root_.scalapb.LiteParser.readMessage(_input__, __value.getOrElse(com.github.sguzman.anime.protoc.items.Anime.defaultInstance)))
            case tag => _input__.skipField(tag)
          }
        }
        com.github.sguzman.anime.protoc.items.Items.CacheEntry(
            key = __key,
            value = __value
        )
      }
      def withKey(__v: _root_.scala.Predef.String): CacheEntry = copy(key = __v)
      def getValue: com.github.sguzman.anime.protoc.items.Anime = value.getOrElse(com.github.sguzman.anime.protoc.items.Anime.defaultInstance)
      def clearValue: CacheEntry = copy(value = None)
      def withValue(__v: com.github.sguzman.anime.protoc.items.Anime): CacheEntry = copy(value = Option(__v))
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.github.sguzman.anime.protoc.items.Items.CacheEntry
  }
  
  object CacheEntry extends scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items.CacheEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items.CacheEntry] = this
    def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.sguzman.anime.protoc.items.Items.CacheEntry = {
      require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
      val __fields = javaDescriptor.getFields
      com.github.sguzman.anime.protoc.items.Items.CacheEntry(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
        __fieldsMap.get(__fields.get(1)).asInstanceOf[scala.Option[com.github.sguzman.anime.protoc.items.Anime]]
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[com.github.sguzman.anime.protoc.items.Items.CacheEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        com.github.sguzman.anime.protoc.items.Items.CacheEntry(
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[scala.Option[com.github.sguzman.anime.protoc.items.Anime]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = com.github.sguzman.anime.protoc.items.Items.javaDescriptor.getNestedTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = com.github.sguzman.anime.protoc.items.Items.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = com.github.sguzman.anime.protoc.items.Anime
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = com.github.sguzman.anime.protoc.items.Items.CacheEntry(
    )
    implicit class CacheEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.anime.protoc.items.Items.CacheEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.github.sguzman.anime.protoc.items.Items.CacheEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.anime.protoc.items.Anime] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[com.github.sguzman.anime.protoc.items.Anime]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)] =
      _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)](__m => (__m.key, __m.getValue))(__p => com.github.sguzman.anime.protoc.items.Items.CacheEntry(__p._1, Some(__p._2)))
  }
  
  @SerialVersionUID(0L)
  final case class AnimeEntry(
      key: _root_.scala.Predef.String = "",
      value: scala.Option[com.github.sguzman.anime.protoc.items.AnimeUser] = None
      ) extends scalapb.GeneratedMessage with scalapb.Message[AnimeEntry] with scalapb.lenses.Updatable[AnimeEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        if (key != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, key) }
        if (value.isDefined) { __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(value.get.serializedSize) + value.get.serializedSize }
        __size
      }
      final override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        };
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.github.sguzman.anime.protoc.items.Items.AnimeEntry = {
        var __key = this.key
        var __value = this.value
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = Option(_root_.scalapb.LiteParser.readMessage(_input__, __value.getOrElse(com.github.sguzman.anime.protoc.items.AnimeUser.defaultInstance)))
            case tag => _input__.skipField(tag)
          }
        }
        com.github.sguzman.anime.protoc.items.Items.AnimeEntry(
            key = __key,
            value = __value
        )
      }
      def withKey(__v: _root_.scala.Predef.String): AnimeEntry = copy(key = __v)
      def getValue: com.github.sguzman.anime.protoc.items.AnimeUser = value.getOrElse(com.github.sguzman.anime.protoc.items.AnimeUser.defaultInstance)
      def clearValue: AnimeEntry = copy(value = None)
      def withValue(__v: com.github.sguzman.anime.protoc.items.AnimeUser): AnimeEntry = copy(value = Option(__v))
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.github.sguzman.anime.protoc.items.Items.AnimeEntry
  }
  
  object AnimeEntry extends scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items.AnimeEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.github.sguzman.anime.protoc.items.Items.AnimeEntry] = this
    def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.sguzman.anime.protoc.items.Items.AnimeEntry = {
      require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
      val __fields = javaDescriptor.getFields
      com.github.sguzman.anime.protoc.items.Items.AnimeEntry(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
        __fieldsMap.get(__fields.get(1)).asInstanceOf[scala.Option[com.github.sguzman.anime.protoc.items.AnimeUser]]
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[com.github.sguzman.anime.protoc.items.Items.AnimeEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        com.github.sguzman.anime.protoc.items.Items.AnimeEntry(
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[scala.Option[com.github.sguzman.anime.protoc.items.AnimeUser]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = com.github.sguzman.anime.protoc.items.Items.javaDescriptor.getNestedTypes.get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = com.github.sguzman.anime.protoc.items.Items.scalaDescriptor.nestedMessages(1)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = com.github.sguzman.anime.protoc.items.AnimeUser
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = com.github.sguzman.anime.protoc.items.Items.AnimeEntry(
    )
    implicit class AnimeEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.anime.protoc.items.Items.AnimeEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.github.sguzman.anime.protoc.items.Items.AnimeEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.anime.protoc.items.AnimeUser] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[com.github.sguzman.anime.protoc.items.AnimeUser]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.AnimeEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)] =
      _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.AnimeEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)](__m => (__m.key, __m.getValue))(__p => com.github.sguzman.anime.protoc.items.Items.AnimeEntry(__p._1, Some(__p._2)))
  }
  
  implicit class ItemsLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.anime.protoc.items.Items]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.github.sguzman.anime.protoc.items.Items](_l) {
    def sums: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[com.github.sguzman.anime.protoc.items.AnimeSummary]] = field(_.sums)((c_, f_) => c_.copy(sums = f_))
    def cache: _root_.scalapb.lenses.Lens[UpperPB, scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime]] = field(_.cache)((c_, f_) => c_.copy(cache = f_))
    def anime: _root_.scalapb.lenses.Lens[UpperPB, scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser]] = field(_.anime)((c_, f_) => c_.copy(anime = f_))
  }
  final val SUMS_FIELD_NUMBER = 1
  final val CACHE_FIELD_NUMBER = 2
  final val ANIME_FIELD_NUMBER = 3
  @transient
  private val _typemapper_cache: _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)] = implicitly[_root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.Anime)]]
  @transient
  private val _typemapper_anime: _root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.AnimeEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)] = implicitly[_root_.scalapb.TypeMapper[com.github.sguzman.anime.protoc.items.Items.AnimeEntry, (_root_.scala.Predef.String, com.github.sguzman.anime.protoc.items.AnimeUser)]]
}
