// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.anime.protoc.items

object ItemsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.github.sguzman.anime.protoc.items.AnimeSummary,
    com.github.sguzman.anime.protoc.items.Anime,
    com.github.sguzman.anime.protoc.items.UserStats,
    com.github.sguzman.anime.protoc.items.AnimeUser,
    com.github.sguzman.anime.protoc.items.Items
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cipjb20vZ2lodWIvc2d1em1hbi9hbmltZS9wcm90b2MvaXRlbXMucHJvdG8SH2NvbS5naXRodWIuc2d1em1hbi5hbmltZS5wc
  m90b2Mi1gEKDEFuaW1lU3VtbWFyeRIUCgV0aXRsZRgBIAEoCVIFdGl0bGUSEAoDaW1nGAIgASgJUgNpbWcSEgoEbGluaxgDIAEoC
  VIEbGluaxISCgRkZXNjGAQgASgJUgRkZXNjEhYKBnN0dWRpbxgFIAEoCVIGc3R1ZGlvEhIKBHllYXIYBiABKAlSBHllYXISFgoGc
  mF0aW5nGAcgASgBUgZyYXRpbmcSGgoIc2hvd1R5cGUYCCABKAlSCHNob3dUeXBlEhYKBmdlbnJlcxgJIAMoCVIGZ2VucmVzIpgBC
  gVBbmltZRJHCgdzdW1tYXJ5GAEgASgLMi0uY29tLmdpdGh1Yi5zZ3V6bWFuLmFuaW1lLnByb3RvYy5BbmltZVN1bW1hcnlSB3N1b
  W1hcnkSEAoDYWx0GAIgASgJUgNhbHQSEgoEcmFuaxgDIAEoDVIEcmFuaxIOCgJpZBgEIAEoBFICaWQSEAoDdXJsGAUgASgJUgN1c
  mwitQEKCVVzZXJTdGF0cxIYCgd3YXRjaGVkGAEgASgNUgd3YXRjaGVkEhoKCHdhdGNoaW5nGAIgASgNUgh3YXRjaGluZxIgCgt3Y
  W50VG9XYXRjaBgDIAEoDVILd2FudFRvV2F0Y2gSGAoHc3RhbGxlZBgEIAEoDVIHc3RhbGxlZBIYCgdkcm9wcGVkGAUgASgNUgdkc
  m9wcGVkEhwKCXdvbnRXYXRjaBgGIAEoDVIJd29udFdhdGNoIokBCglBbmltZVVzZXISPAoFYW5pbWUYASABKAsyJi5jb20uZ2l0a
  HViLnNndXptYW4uYW5pbWUucHJvdG9jLkFuaW1lUgVhbmltZRI+CgR1c2VyGAIgASgLMiouY29tLmdpdGh1Yi5zZ3V6bWFuLmFua
  W1lLnByb3RvYy5Vc2VyU3RhdHNSBHVzZXIipAMKBUl0ZW1zEkEKBHN1bXMYASADKAsyLS5jb20uZ2l0aHViLnNndXptYW4uYW5pb
  WUucHJvdG9jLkFuaW1lU3VtbWFyeVIEc3VtcxJHCgVjYWNoZRgCIAMoCzIxLmNvbS5naXRodWIuc2d1em1hbi5hbmltZS5wcm90b
  2MuSXRlbXMuQ2FjaGVFbnRyeVIFY2FjaGUSRwoFYW5pbWUYAyADKAsyMS5jb20uZ2l0aHViLnNndXptYW4uYW5pbWUucHJvdG9jL
  kl0ZW1zLkFuaW1lRW50cnlSBWFuaW1lGmAKCkNhY2hlRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSPAoFdmFsdWUYAiABKAsyJi5jb
  20uZ2l0aHViLnNndXptYW4uYW5pbWUucHJvdG9jLkFuaW1lUgV2YWx1ZToCOAEaZAoKQW5pbWVFbnRyeRIQCgNrZXkYASABKAlSA
  2tleRJACgV2YWx1ZRgCIAEoCzIqLmNvbS5naXRodWIuc2d1em1hbi5hbmltZS5wcm90b2MuQW5pbWVVc2VyUgV2YWx1ZToCOAFiB
  nByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}