// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.anime.protoc.store

object StoreProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.github.sguzman.anime.protoc.items.ItemsProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.github.sguzman.anime.protoc.store.StoreCache
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cipjb20vZ2lodWIvc2d1em1hbi9hbmltZS9wcm90b2Mvc3RvcmUucHJvdG8SH2NvbS5naXRodWIuc2d1em1hbi5hbmltZS5wc
  m90b2MaKmNvbS9naWh1Yi9zZ3V6bWFuL2FuaW1lL3Byb3RvYy9pdGVtcy5wcm90byLAAQoKU3RvcmVDYWNoZRJMCgVjYWNoZRgBI
  AMoCzI2LmNvbS5naXRodWIuc2d1em1hbi5hbmltZS5wcm90b2MuU3RvcmVDYWNoZS5DYWNoZUVudHJ5UgVjYWNoZRpkCgpDYWNoZ
  UVudHJ5EhAKA2tleRgBIAEoCVIDa2V5EkAKBXZhbHVlGAIgASgLMiouY29tLmdpdGh1Yi5zZ3V6bWFuLmFuaW1lLnByb3RvYy5Bb
  mltZVVzZXJSBXZhbHVlOgI4AWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.github.sguzman.anime.protoc.items.ItemsProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}